personal_website/blog/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
        home_view, 
        article_list_view, 
        post_detail_view, 
        create_article_view, 
        PostDetailView, change_votes
)

urlpatterns = [
    path('', home_view, name='article-home'),
    path('article/all', article_list_view, name='article-list'),
    path('article/detail/<slug:slug>/', PostDetailView.as_view(), name='article-detail'),
    path('article/create/', create_article_view, name='create-article'),
    path('article/change-vote/', change_votes, name='change-at-vote'),  
]

personal_website/personal_website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('auth/', include('authuser.urls')),
    path('community/', include('qna.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('', include('landing.urls')),
    path('codes/', include('code_arena.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_website/qna/urls.py
from django.urls import path
from .views import (
    HomeView, QuestionDetailView, create_question_view,
    question_list_view, change_votes
)

urlpatterns = [
    path('', HomeView.as_view(), name='qna-home'),
    path('question/all', question_list_view, name='qna-list'),
    path('question/detail/<slug:slug>/', QuestionDetailView.as_view(), name='qna-detail'),
    path('question/create/', create_question_view, name='qna-create'),  
    path('question/change-vote/', change_votes, name='change-vote'),  
    path('question/post-answer/', change_votes, name='post-answer'),  
]

personal_website/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False, blank=True, null=True)
    topic_related_to = models.CharField(max_length=400, blank=True, null=True)
    title = models.CharField(max_length=200)
    content = RichTextField(blank=True, null=True)
    published = models.BooleanField(default=False, blank=True, null=True)
    tags = TaggableManager(blank=True)
    upvotes = models.IntegerField(default=0, blank=True, null=True)
    downvotes = models.IntegerField(default=0, blank=True, null=True)
    thumbnail = models.ImageField(blank=True, null=True)
    published_on = models.DateField(auto_now_add=True, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    
    def __str__(self):
        return "Article \"{}\" of Author {}".format(self.title, self.author)

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("article-detail", kwargs={
            'slug': self.slug
        })

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, blank=True, null=True)
    # comment_author = models.ForeignKey(User, on_delete=models.CASCADE) 
    comment_author = models.CharField(max_length=200)
    comment_body = models.TextField(blank=True, null=True)
    upvotes = models.IntegerField(default=0, blank=True, null=True)
    downvotes = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return "comment {} of article {}".format(self.id, self.article)
        

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.SET_NULL, blank=True, null=True)
    reply_author = models.CharField(max_length=200)
    reply_body = models.TextField(blank=True, null=True)


def get_all_related_topic(): 
    articles = Article.objects.all()
    related_topics = []
    for article in articles:
        related_topics.append(article.topic_related_to)

    return related_topics

personal_website/authuser/forms.py
from .models import  UserProfile
from django import forms 
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.password_validation import password_validators_help_text_html
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class SignupUserForm(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        required=False, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    first_name = forms.CharField(
        label="First name", 
        required=False, 
        max_length=100, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    last_name = forms.CharField(
        label="Last name", 
        required=False, 
        max_length=100, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    bio = forms.CharField(
        label="Bio", 
        required=False, 
        max_length=1000, 
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        )
    )
    
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                #'style': 'width: 500px',
                'autocomplete': 'new-password',
            }
        ), 
        help_text=password_validators_help_text_html()
    )

    password2 = forms.CharField(
        label="Re-enter Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'new-password',
            }
        ), 
        help_text=("Enter the same password as before, for verification.")
    )

    image = forms.ImageField(
        allow_empty_file=True, 
        required=False,
        # widget=forms.ImageField()
    )


    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "bio",
            "password1",
            "password2",
            "image"
        ]
        
        def clean_username(self):
            username = self.cleaned_data['username']
            if len(username) < 2:
                raise forms.ValidationError("Username is too short")
            elif User.objects.get_object_or_404(username=username):
                raise forms.ValidationError("This username is already taken")
            return username


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )


class EditUserForm(forms.ModelForm):
    email = forms.EmailField(
        label="Email",
        required=False, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    first_name = forms.CharField(
        label="First name", 
        required=False, 
        max_length=100, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    last_name = forms.CharField(
        label="Last name", 
        required=False, 
        max_length=100, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    username = UsernameField(
        required=False, 
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    bio = forms.CharField(
        label="Bio", 
        required=False, 
        max_length=1000, 
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        )
    )

    image = forms.ImageField(
        allow_empty_file=True, 
        required=False,
        # widget=forms.ImageField()
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "bio",
            "image"
        ]

personal_website/blog/forms.py
from django import forms 
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget
from django.forms import fields
from .models import Article, Comment, Reply


class CommentForm(forms.ModelForm): 
    comment_author = forms.CharField(
        label="Your Name",
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )

    comment_body = forms.CharField(
        label="Comment Body",
        max_length=200,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
        })
    )
    

    class Meta:
        model = Comment
        fields = ['comment_author', 'comment_body']


class ReplyForm(forms.ModelForm): 
    reply_body = forms.CharField(
        label="Reply Body",
        max_length=200,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
        })
    )

    class Meta:
        model = Comment
        fields = ['comment_body']


class ArticlePostForm(forms.ModelForm):
    title = forms.CharField(
        label="Post Title",
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    content = forms.CharField(
        label="Post Content",
        max_length=2000,
        widget=CKEditorWidget()
    )
    topic_related_to = forms.CharField(
        required=False,
        label='Post Topic related to', 
        max_length=400,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    tags = forms.CharField(
        required=False,
        label="Enter Tags related to your Post",
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
        })
    )
    thumbnail = forms.ImageField(required=False)

    class Meta:
        model = Article
        fields = [
            "title",
            "content",
            "topic_related_to",
            "tags",
            "thumbnail",
        ]

personal_website/blog/views.py
from django import views
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.core.files.uploadedfile import SimpleUploadedFile
from django.http import JsonResponse
from .models import Article, get_all_related_topic, Comment, Reply
from .forms import ArticlePostForm, CommentForm

import json

# Create your views here.


def home_view(request):
    template_name = 'blog/home.html'
    articles = Article.objects.filter(featured=True)

    context = {
        "articles": articles
    }
    return render(request, context=context, template_name=template_name)
    
def article_list_view(request):
    template_name = 'blog/article-list.html'
    articles = Article.objects.all()
    related_topics = get_all_related_topic()

    context = {
        "articles": articles,
        "related_topics": related_topics
    }
    return render(request, template_name=template_name, context=context)  
  
def post_detail_view(request, slug):
    context = {}
    template_name = 'blog/detail-page.html'
    selected_article = get_object_or_404(Article, slug=slug)
    related_articles = Article.objects.all()
    comments = Comment.objects.filter(article=selected_article)

    if request.method == "POST":
        form = CommentForm(request.POST or None)
        if form.is_valid():
            new_comment = Comment.objects.create(
                article=selected_article,
                comment_author=form.cleaned_data['comment_author'], 
                comment_body = form.cleaned_data['comment_body'],
            )
            new_comment.save()
            messages.success(request, "Comment posted!")
            return redirect('article-home')
    else:
        form = CommentForm()
        context['form'] = form
        
    return render(request, context={'article': selected_article, 'related_articles': related_articles, 'comments': comments}, template_name=template_name)


class PostDetailView(views.View):
    template_name = 'blog/detail-page.html'
    context = {}
    
    def get(self, *args, **kwargs):
        selected_article = get_object_or_404(Article, slug=kwargs['slug'])
        related_articles = Article.objects.all()
        comments = Comment.objects.filter(article=selected_article)
        form = CommentForm()
        self.context['form'] = form

        context = {
            'article': selected_article,
            'related_articles': related_articles, 
            'comments': comments,
            'comment_count': comments.count()
        }
        
        self.context.update(context)
        return render(self.request, self.template_name, context=self.context)
    
    # @login_required(login_url='/auth/login/')
    def post(self, *args, slug, **kwargs):
        
        # if self.request.user == 'AnonymousUser':
        #     return redirect('user-login')
        
        form = CommentForm(self.request.POST)     
        selected_article = get_object_or_404(Article, slug=slug)
        print(selected_article)
        if form.is_valid():

            new_comment = Comment.objects.create(
                article=selected_article,
                comment_author=form.cleaned_data['comment_author'], 
                # comment_author = self.request.user.full_name,
                comment_body = form.cleaned_data['comment_body'],
            )        
            new_comment.save()
            messages.success(self.request, "Comment posted!")
            return redirect('/blog/article/detail/'+slug)

        else:
            print("Please fill the form correctly")
            messages.warning(self.request, "Please fill the form correctly");
            return redirect('article-detail')


@login_required(login_url='/auth/login/')
def create_article_view(request):
    template_name = 'blog/article_form.html'
    context = {}
    if request.method == "POST":
        form = ArticlePostForm(request.POST, request.FILES or None)
        print(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            new_article = Article.objects.create(
                author=request.user, 
                topic_related_to = form.cleaned_data['topic_related_to'],
                title = form.cleaned_data['title'],
                content = form.cleaned_data['content'],
                tags = form.cleaned_data['tags'],
                thumbnail = form.cleaned_data.get('thumbnail'),
            )
            new_article.save()
            messages.success(request, "Post will be published Soon!")
            return redirect('article-home')
    else:
        form = ArticlePostForm()
        context['form'] = form
    
    return render(request, template_name, context=context)


def change_votes(request):
    response_body = json.loads(request.body)

    if response_body['action'] == 'at-upvote':
        article = Article.objects.get(id=response_body['id'])
        article.upvotes += 1
        article.save()
    elif response_body['action'] == 'at-downvote':
        print("Action Triggered")
        article = Article.objects.get(id=response_body['id'])
        article.downvotes += 1
        article.save()

    # elif response_body['action'] == 'ans-upvote':
    #     print("Action Triggered")
    #     answer = Comment.objects.get(id=response_body['id'])
    #     answer.upvotes += 1
    #     answer.save()
    # elif response_body['action'] == 'ans-downvote':
    #     print("Action Triggered")
    #     answer = Comment.objects.get(id=response_body['id'])
    #     answer.downvotes += 1
    #     answer.save()

    return JsonResponse('Item is added', safe=False)

personal_website/templates/blog/article-list.html
{% extends 'blog/base-blog.html' %}

{% load static %}
{% block extra_head %}
{% endblock %}

<body>
  {% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-5">
    <div class="container">

      <!--Section: Jumbotron-->
      <section class="card young-passion-gradient wow fadeIn">

        <!-- Content -->
        <div class="card-body text-white text-center py-5 px-5 my-5">

          <h1 class="mb-4">
            <strong>Explore High Quality Knowledgable Tech Articles</strong>
          </h1>
          <p>
            <strong>Articles from developers, engineers, experienced industrial person and enthusiast students</strong>
          </p>

          <a href="#articles" class="btn btn-outline-white btn-md">
            Explore Articles <i class="fas fa-explore ml-2"></i>
          </a>

        </div>
        <!-- Content -->
      </section>
      <!--Section: Jumbotron-->

      <!--Section: Cards-->
      <section class="pt-5" id="articles">

        <!-- Heading & Description -->
        <div class="wow fadeIn content">
          <hr class="mb-5">
          <!--Section heading-->
          <h2 class="h3 text-center mb-4">Categories</h2>
          <!--Section description-->
          <p class="h5 text-center">Choose your catagory of Articles</p>
          <div class="my-3">
            <div class="row wow fadeIn">
              {% for topic in related_topics %}
              <div class="col-sm-2">
                <a class="" href>{{topic}}</a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <!-- Heading & Description -->
        <hr class="mb-5">

        {% for article in articles %}
        <!--Grid row-->
        <div class="row wow fadeIn bg-white">

          <!--Grid column-->
          <div class="col-md-5 col-lg-4 mb-4 mt-4">
            <!--Featured image-->
            <div class="view overlay rounded z-depth-1-half">
              <div class="view overlay">
                <div class="embed-responsive embed-responsive-16by9">
                  <img class="embed-responsive-item"
                    src="{% if article.imageURL %}{{article.imageURL}} {% else %} {% static 'images/article_dummy.png' %} {% endif %}"></img>
                </div>
              </div>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-7 col-lg-7 ml-xl-4 mb-4 mt-4">
            <h3 class="mb-3 font-weight-bold dark-grey-text">
              <strong>{{article.title}}</strong>
            </h3>
            <p class="card-text">Written by <strong>{{article.author}}</strong></p>
            <p class="card-text">Topic related to: <strong>{{article.topic_related_to}}</strong></p>
            <p class="card-text">Tags: {{article.topic_related_to}}</p>
            <a href="{{article.get_absolute_url}}" class="btn btn-primary btn-md">Read Article
              <i class="fas fa-book ml-2"></i>
            </a>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr class="mb-5">
        {% endfor %}

        <!--Pagination-->
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            <!--Arrow left-->
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>

            <li class="page-item active">
              <a class="page-link" href="#">1
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">4</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">5</a>
            </li>

            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </nav>
        <!--Pagination-->

      </section>
      <!--Section: Cards-->

    </div>
  </main>
  <!--Main layout-->
  {% endblock %}

personal_website/templates/blog/article_form.html
{% extends 'blog/base-blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    div.django-ckeditor-widget {
        /* margin: 2px !important;
    background-color: black !important; */
    }
</style>
<main class="mt-5 pt-5">
    <div class="container">
        <section class="card wow fadeIn"
            style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
            <div class="card-body text-white py-5 px-5 my-5">
                <h1 class="my-4">
                    <strong>Post Article</strong>
                </h1>
                <form method="POST" class="">
                    {% csrf_token %}
                    <div class="form-group form-row">
                        <div class=" col-md-6">
                            {{ form.title|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-group form-row">
                        <div class=" col-md-12">
                            {{ form.content | as_crispy_field}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.topic_related_to|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.tags|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-group form-row">
                        <div class="form-group col-md-8 mb-0">
                            {{ form.thumbnail }}
                        </div>
                    </div>
                    {{form.media}}

                    <button type="submit" class="btn btn-primary btn-block mb-4">Post Article</button>
                </form>
            </div>
        </section>
    </div>
</main>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.15.0/ckeditor.js" integrity="sha512-bNMnTgKRxN1n+5rgfcf160HT2koHRcwLcSq/3JDOY9R65mja48E4Hh+a+IQXVaY2NoJCVC+pr0qE3Vz194QwnA==" crossorigin="anonymous"></script> -->
<script>    
    // CKEDITOR.replace('{{ form.content.id_for_label }}', {
    //     // plugins: 'wysiwygarea, toolbar, basicstyles, link, paste tools, preview, print, find,  '
    //     // plugins: 'wysiwygarea, toolbar, basicstyles, a11yhelp, about, adobeair, autoembed, autogrow, autolink, bbcode, clipboard, codesnippet, codesnippetgeshi, colordialog, devtools, dialog, div, divarea, docprops, embed, embedbase, embedsemantic, filetools, find, flash, forms, iframe, iframedialog, image, image2, language, lineutils, link, liststyle, magicline, mathjax, menubutton, notification, notificationaggregator,pagebreak, pastefromword, placeholder, preview, scayt, sharedspace, showblocks, smiley, sourcedialog, specialchar, stylesheetparser, table, tableresize, tabletools, templates, uicolor, uploadimage, uploadwidget, widget, wsc, xml'
    // })
</script>
{% endblock %}

personal_website/templates/blog/base-blog.html
{% extends 'base.html' %}

{% block body %}
{% block bodyclass %}heavy-rain-gradient{% endblock %}
    <header>
        {% include 'blog/navbar.html' %}
    </header>
    <div class="">
        {% block content %}
        {% endblock %}
    </div>
    {% include "blog/footer.html" %}
{% endblock %}

personal_website/templates/blog/helper.html
<!-- Signup Form Fields-->
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control"  id="id_username" type="text" name="username" maxlength="100" required>
            <label class="form-label" for="id_username">Username:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control" type="text" name="first_name" id="id_first_name" required>
            <label class="form-label" for="id_first_name">FirstName:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control" type="text" name="last_name" id="id_last_name" required>
            <label class="form-label" for="id_last_name">LastName:</label>
        <div class="form-outline mb-4">
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control" type="email" name="email" id="id_email" required>
            <label class="form-label" for="id_email">Email:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control" type="password" name="password1" id="id_password1">
            <label class="form-label" for="id_password1">Password:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4">
            <input class="form-control" type="password" name="password2" id="id_password2">
            <label class="form-label" for="id_password2">Re-Enter Password:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
            <label class="form-label" for="id_image">Image:</label>
            <input class="form-control" type="file" name="image" id="id_image">
    </div>
</div>

<div class="pt-4">
    <button type="submit" class="btn btn-primary active">Sign Up</button>
</div>



<!-- Signup Form Fields-->
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.username|as_crispy_field }}
        {{ form.username.errors }}
    </div>
</div>
<div class="form-group form-row">
    <div class=" col-md-8">
        {{ form.first_name.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.first_name|as_crispy_field }}
    </div>
</div>
<div class="form-group form-row">
    <div class=" col-md-8">
        {{ form.last_name.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.last_name|as_crispy_field}}
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.email|as_crispy_field }}
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.password1.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.password1|as_crispy_field }}
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.password2.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.password2|as_crispy_field }}
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.image.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.image|as_crispy_field }}
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        {{ form.bio.errors }}
    </div>
    <div class=" col-md-8">
        {{ form.bio|as_crispy_field }}
    </div>
</div>

<div class="pt-4">
    <button type="submit" class="btn btn-primary active">Sign Up</button>
</div>


<!-- Signup Form Fields -->
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" id="id_username" type="text" name="username" maxlength="100"
                required>
            <label class="form-label" for="id_username">Username:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" type="text" name="first_name" id="id_first_name" required>
            <label class="form-label" for="id_first_name">FirstName:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" type="text" name="last_name" id="id_last_name" required>
            <label class="form-label" for="id_last_name">LastName:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" type="email" name="email" id="id_email" required>
            <label class="form-label" for="id_email">Email:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <textarea class="form-control" name="email"  rows=6 id="id_email"></textarea>
            <label class="form-label" for="id_email">Bio</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" type="password" name="password1" id="id_password1">
            <label class="form-label" for="id_password1">Password:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0">
        <div class="form-outline mb-4 p-2">
            <input class="form-control" type="password" name="password2" id="id_password2">
            <label class="form-label" for="id_password2">Re-Enter Password:</label>
        </div>
    </div>
</div>
<div class="form-group form-row">
    <div class="form-group col-md-8 mb-0 p-2">
        <label class="form-label" for="id_image">Image:</label>
        <input class="form-control" type="file" name="image" id="id_image">
    </div>
</div>